// Z-index layers used across the SDK
export const Z_INDEX = {
  LOADING_OVERLAY: 10000,
  SHEET_OVERLAY: 10000,
  SHEET_CLOSE_BTN: 10005,
  SHEET_CONFIRM_MODAL: 10010,
  SELECT_COMBOBOX: 10020,
  MISSING_FIELDS_MODAL: 10050,
  PROGRESS_TOAST: 10050,
  PORTAL_ROOT: 9999,
} as const;

// Layout dimensions
export const LAYOUT = {
  REVIEW_ROW_HEIGHT: 32,
  REVIEW_VIEWPORT_HEIGHT: 600,
  REVIEW_OVERSCAN: 8,
  REVIEW_OVERSCAN_HALF: 4,
  MANUAL_ROW_HEIGHT: 24,
  MIN_COLUMN_WIDTH: 120,
  ACTIONS_COLUMN_WIDTH: 80,
  SHEET_MODAL_MAX_WIDTH: 1200,
  SHEET_MODAL_WIDTH: "90%",
  MIN_CONTENT_HEIGHT: 600,
  MIN_TABLE_HEIGHT: 400,
  MAPPING_PANEL_HEIGHT: 500,
  MAPPING_SCROLL_HEIGHT: 440,
  MISSING_MODAL_MAX_HEIGHT: 180,
  PROGRESS_TOAST_WIDTH: 240,
} as const;

// Processing defaults
export const PROCESSING = {
  DEFAULT_CHUNK_SIZE: 2000,
  DEFAULT_CONFIDENCE_THRESHOLD: 0.7,
  VALIDATION_DEBOUNCE_MS: 300,
  UNPIN_DELAY_MS: 120,
  ENCODING_SAMPLE_SIZE: 512 * 1024,
  PREVIEW_ROWS: 5,
  PREVIEW_SAMPLE_VALUES: 10,
  PROGRESS_THROTTLE_MS: 100,
} as const;
